import 'package:flutter/material.dart';

class AppTheme extends ChangeNotifier {
  String _language = 'en'; // 'en' for English, 'fr' for French

  String get language => _language;

  void setLanguage(String lang) {
    _language = lang;
    notifyListeners();
  }

  ThemeData getTheme() {
    const primary = Color(0xFF1F4788); // Professional Blue
    const secondary = Color(0xFF00A3FF);
    const error = Color(0xFFE74C3C);

    return ThemeData(
      useMaterial3: true,
      brightness: Brightness.light,
      primaryColor: primary,
      scaffoldBackgroundColor: const Color(0xFFFAFAFC),
      colorScheme: const ColorScheme.light(
        primary: primary,
        secondary: secondary,
        tertiary: Color(0xFF616161),
        error: error,
        surface: Colors.white,
        onSurface: Color(0xFF1A1A1A),
      ),
      // AppBar
      appBarTheme: const AppBarTheme(
        backgroundColor: Colors.white,
        elevation: 1,
        centerTitle: false,
        titleTextStyle: TextStyle(
          color: Color(0xFF1A1A1A),
          fontSize: 20,
          fontWeight: FontWeight.w600,
        ),
      ),
      // Text Themes
      textTheme: const TextTheme(
        headlineLarge: TextStyle(
          fontSize: 32,
          fontWeight: FontWeight.bold,
          color: Color(0xFF1A1A1A),
        ),
        headlineMedium: TextStyle(
          fontSize: 26,
          fontWeight: FontWeight.bold,
          color: Color(0xFF1A1A1A),
        ),
        headlineSmall: TextStyle(
          fontSize: 20,
          fontWeight: FontWeight.w600,
          color: Color(0xFF1A1A1A),
        ),
        titleLarge: TextStyle(
          fontSize: 18,
          fontWeight: FontWeight.w600,
          color: Color(0xFF1A1A1A),
        ),
        bodyLarge: TextStyle(
          fontSize: 16,
          fontWeight: FontWeight.w500,
          color: Color(0xFF1A1A1A),
        ),
        bodyMedium: TextStyle(
          fontSize: 14,
          fontWeight: FontWeight.normal,
          color: Color(0xFF616161),
        ),
        labelSmall: TextStyle(
          fontSize: 12,
          fontWeight: FontWeight.w500,
          color: Color(0xFF9E9E9E),
        ),
      ),
      // Button Themes
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: primary,
          foregroundColor: Colors.white,
          padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12),
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(8),
          ),
          elevation: 2,
        ),
      ),
      // Input Decoration
      inputDecorationTheme: InputDecorationTheme(
        filled: true,
        fillColor: const Color(0xFFF5F5F5),
        hintStyle: const TextStyle(color: Color(0xFF9E9E9E)),
        labelStyle: const TextStyle(color: Color(0xFF616161)),
        contentPadding:
            const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(8),
          borderSide: const BorderSide(color: Color(0xFFDEE0E6)),
        ),
        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(8),
          borderSide: const BorderSide(color: Color(0xFFDEE0E6), width: 1),
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.circular(8),
          borderSide: const BorderSide(color: primary, width: 2),
        ),
      ),
      // Card Theme
      cardTheme: CardTheme(
        color: Colors.white,
        elevation: 2,
        margin: EdgeInsets.zero,
        shape: RoundedRectangleBorder(
          borderRadius: BorderRadius.circular(12),
          side: const BorderSide(color: Color(0xFFDEE0E6), width: 1),
        ),
      ),
    );
  }

  String translate(String key) {
    final translations = {
      'en': {
        'dashboard': 'Dashboard',
        'offer': 'Offer',
        'rh': 'RH',
        'personal': 'Personal',
        'news': 'News & Events',
        'jackpot': 'My Jackpot',
        'applications': 'My Applications',
        'communication': 'Communication',
        'profile': 'Profile',
        'logout': 'Logout',
        'my_cra': 'My CRA',
        'my_expenses': 'My Expenses',
        'calendar': 'Calendar',
        'my_tasks': 'My Tasks',
        'news_events': 'News & Events',
        'postes': 'Job Offers',
        'chats': 'Chats',
        'feedbacks': 'Feedbacks',
        'documents': 'Documents',
        'send_feedback': 'Send feedback to admin support',
        'describe_feedback': 'Describe your feedback',
        'send': 'Send',
        'feedback_sent': 'Feedback sent successfully!',
        'first_name': 'First name',
        'enter_first_name': 'Enter first name',
        'last_name': 'Last name',
        'enter_last_name': 'Enter last name',
        'category': 'Category',
        'select': 'Select...',
        'phone': 'Phone',
        'enter_phone': 'Enter phone',
        'email': 'Email',
        'enter_email': 'Enter email',
        'daily_role': 'Daily Role',
        'enter_daily_role': 'Enter daily role',
        'summary': 'Summary',
        'enter_summary': 'Enter summary',
        'informations': 'General Information',
        'domain_skills': 'Domain Skills',
        'professional_skills': 'Professional Skills',
        'experiences': 'Experiences',
        'technical_skills': 'Technical Skills',
        'education_history': 'Education History',
        'languages': 'Languages',
        'certifications': 'Certifications',
        'training': 'Training',
        'save': 'Save',
        'add_new': 'Add New...',
        'no_items': 'No items added yet',
        'offers': 'Offers',
        'apply': 'Apply',
        'cra_tracking': 'CRA Tracking',
        'events': 'Events',
        'cooptation': 'My Cooptation',
        'challenge': 'My Challenge',
        'results': 'My Results',
        // Additional translations
        'add_task': 'Add Task',
        'my_news': 'News',
        'delete': 'Delete',
        'edit': 'Edit',
        'close': 'Close',
        'cancel': 'Cancel',
        'search': 'Search',
        'no_data': 'No data available',
        'error': 'Error',
        'success': 'Success',
        'loading': 'Loading...',
        'empty': 'Empty',
        'back': 'Back',
        'next': 'Next',
        'previous': 'Previous',
        'view_all': 'View All',
        'more': 'More',
        'less': 'Less',
        'yes': 'Yes',
        'no': 'No',
        'ok': 'OK',
        'company': 'Company',
        'location': 'Location',
        'price': 'Price',
        'type': 'Type',
        'remote': 'Remote',
        'hybrid': 'Hybrid',
        'on_site': 'On Site',
        'rate': 'Rate',
        'description': 'Description',
        'posted_on': 'Posted on',
        'start_date': 'Start Date',
        'experience': 'Experience',
        'candidates': 'Candidates',
        'expired': 'Expired',
        'active': 'Active',
        'pending': 'Pending',
        'completed': 'Completed',
        'in_progress': 'In Progress',
        'online': 'Online',
        'offline': 'Offline',
        'message': 'Message',
        'send_message': 'Send Message',
        'type_message': 'Type your message...',
        'document': 'Document',
        'upload': 'Upload',
        'download': 'Download',
        'delete_confirm': 'Are you sure you want to delete?',
        'expense': 'Expense',
        'amount': 'Amount',
        'date': 'Date',
        'description_short': 'Desc.',
        'status': 'Status',
        'no_conversations': 'No conversations',
        'no_documents': 'No documents',
        'no_expenses': 'No expenses',
        // Dashboard translations
        'statistics': 'Statistics',
        'current_month': 'CURRENT MONTH',
        'since_entry': 'SINCE ENTRY',
        'total_ca': 'Total CA',
        'reserve': 'Reserve',
        'usable_reserve_ca': 'Usable Reserve (CA)',
        'usable_reserve_days': 'Usable Reserve (in days)',
        'ca_since_entry': 'CA Since Entry',
        'reserve_since_entry': 'Reserve Since Entry',
        'usable_reserve_since_entry': 'Usable Reserve Since Entry',
        'usable_reserve_since_entry_days':
            'Usable Reserve Since Entry (in days)',
        'congratulations': 'Congratulations',
        'my_cooptation_evolution': 'My Cooptation Evolution',
        'evolution_per_year': 'Evolution Per Year',
        'scoring_chart': 'Scoring Chart',
        'evolution_application': 'Evolution Application',
        'jackpot_report': 'Jackpot Report / Month',
        'earned': 'Earned',
        'withdrawn': 'Withdrawn',
        'leader_board': 'Leader Board',
        'your_rank': 'Your rank is Top',
        // Profile translations
        'domain_skills_full': 'Domain Skills',
        'functional_skills': 'Functional Skills',
        'level_beginner': 'Beginner',
        'level_intermediate': 'Intermediate',
        'level_advanced': 'Advanced',
        'level_expert': 'Expert',
        'add_skill': 'Add Skill',
        'skill_name': 'Skill Name',
        'select_level': 'Select Level',
        'post': 'Post',
        'position': 'Position',
        'daily_rate': 'Daily Rate',
        'education_degree': 'Degree',
        'education_school': 'School',
        'education_year': 'Year',
        'experience_title': 'Title',
        'experience_company': 'Company',
        'experience_start': 'Start Date',
        'experience_end': 'End Date',
        'experience_description': 'Description',
        'certification_name': 'Certification Name',
        'certification_org': 'Organization',
        'certification_year': 'Year',
        'training_title': 'Title',
        'training_org': 'Organization',
        'training_year': 'Year',
        // News/Events translations
        'read_more': 'Read More',
        'published': 'Published',
        'updated': 'Updated',
        'breaking_news': 'Breaking News',
        'featured': 'Featured',
        // Chat translations
        'no_contacts': 'No contacts',
        'start_conversation': 'Start a conversation',
        'write_message': 'Write your message...',
        'message_sent': 'Message sent',
        // Offer translations
        'job_title': 'Job Title',
        'remote_work': 'Remote Work',
        'mode': 'Mode',
        'duration': 'Duration',
        'contract_type': 'Contract Type',
        'required_skills': 'Required Skills',
        'job_description': 'Job Description',
        'cdd': 'Fixed-term contract',
        'cdi': 'Permanent contract',
        'freelance': 'Freelance',
        'part_time': 'Part-time',
        // Expense translations
        'expense_date': 'Expense Date',
        'expense_category': 'Category',
        'expense_amount': 'Amount',
        'expense_description': 'Description',
        'total_expenses': 'Total Expenses',
        'monthly_expenses': 'Monthly Expenses',
        // CRA translations
        'cra_period': 'CRA Period',
        'cra_status': 'Status',
        'cra_rate': 'Rate',
        'cra_hours': 'Hours',
        'cra_days': 'Days',
        // Task translations
        'add_new_task': 'Add New Task',
        'task_title': 'Task Title',
        'task_priority': 'Priority',
        'task_deadline': 'Deadline',
        'task_status': 'Status',
        'high': 'High',
        'medium': 'Medium',
        'low': 'Low',
        'mark_complete': 'Mark as Complete',
        'mark_important': 'Mark as Important',
        'my_tasks_filter': 'My Tasks',
        'important_tasks': 'Important',
        'completed_tasks': 'Completed',
        'deleted_tasks': 'Deleted',
        // Login screen
        'login_welcome': 'Welcome to Cooptalite! 👋',
        'login_email_label': 'Email',
        'login_email_hint': 'john',
        'login_password_label': 'Password',
        'login_password_forgot': 'Forgot Password?',
        'login_password_hint': '••••••••••',
        'login_button_signin': 'Sign in',
        'login_guest_question': 'Freelancer or Employee?',
        'login_guest_create': 'Create Account as Guest',
        // Profile additions
        'profile_section_experiences': 'Experiences',
        'profile_company_name_hint': 'Company name',
        'profile_date_format': 'MM/YYYY',
        'profile_describe_role_hint': 'Describe your role...',
        'profile_section_education': 'Education history',
        'profile_institution_hint': 'Institution',
        'profile_year_hint': 'e.g. 2021',
        'profile_section_languages': 'Languages',
        'profile_add_language': 'Add new Language',
        'profile_section_certifications': 'Certifications',
        'profile_section_training': 'Training',
        // Offer screen
        'offers_list_title': 'List of offers',
        'offers_type_remote': 'Remote',
        'offers_type_hybrid': 'Hybrid',
        'offers_type_onsite': 'On Site',
        'offers_category_it': 'IT',
        'offers_category_network': 'Network',
        'offers_category_telecom': 'Telecom',
        'offers_category_dev': 'Development',
        'offers_category_data': 'Data',
        'offers_category_cyber': 'Cybersecurity',
        'offers_category_devops': 'DevOps',
        'offers_category_infra': 'Infrastructure',
        'offers_category_pm': 'Project Management',
        'offers_category_qa': 'QA',
        'offers_category_sysinfo': 'System Admin',
        'offers_contract_cdd': 'Fixed-Term',
        'offers_contract_cdi': 'Permanent',
        'offers_contract_freelance': 'Freelance',
        'offers_contract_parttime': 'Part-Time',
        'offers_sort_rate_asc': 'Rate ↑',
        'offers_sort_rate_desc': 'Rate ↓',
        'offers_sort_start': 'Start Date',
        'offers_contact_prefix': 'Contact',
        // Chat additions
        'chat_search_hint': 'Search or start a new chat',
        'chat_contacts_label': 'Contacts',
        'chat_online': 'Online',
        'chat_offline': 'Offline',
        'chat_message_hint': 'Write a message...',
        'chat_empty_title': 'Start Conversation',
        // Expense additions
        'expense_category_transport': 'Transport',
        'expense_category_meal': 'Meal',
        'expense_category_accommodation': 'Accommodation',
        'expense_category_other': 'Other',
        'expense_screen_title': 'My Expenses',
        'expense_screen_subtitle': 'Manage your expense reports',
        'expense_stat_total': 'Total',
        'expense_stat_count': 'Expenses',
        'expense_search_hint': 'Search...',
        'expense_filter_all': 'All',
        'expense_button_add': 'Add an expense',
        'expense_table_title': 'Title',
        'expense_table_category': 'Category',
        'expense_table_date': 'Date',
        'expense_table_amount': 'Amount',
        'expense_table_actions': 'Actions',
        'expense_empty_message': 'No expenses found',
        'expense_dialog_add_title': 'Add an expense',
        'expense_dialog_amount_label': 'Amount (€) *',
        // Events additions
        'events_breadcrumb_home': 'Home',
        'events_breadcrumb_actu': 'News & Events',
        'events_breadcrumb_list': 'List of Events',
        'events_filter_title': 'Title Search:',
        'events_filter_start': 'Start Date Search:',
        'events_filter_end': 'End Date Search:',
        'events_date_format_hint': 'YYYY-MM-DD',
        'events_empty_message': 'No events found',
        'events_start_label': 'Start on',
        'events_end_label': 'End on',
        'events_no_image': 'No Image Available',
        'events_button_details': 'Show Details',
        // Postes additions
        'postes_screen_title': 'Job Posts',
        'postes_breadcrumb_home': 'Home',
        'postes_breadcrumb_postes': 'Posts',
        'postes_button_coopt': 'Coopt a Talented Employee',
        'postes_search_hint': 'Search',
        'postes_button_add': 'Add Post',
        'postes_button_view_my': 'See My Posts',
        'postes_empty_message': 'No posts found',
        'postes_posted_by': 'Posted By:',
        'postes_comments_label': 'Comments',
        'postes_button_read_more': 'Read More',
        'postes_dialog_add_title': 'Add Post',
        'postes_form_title_label': 'Title *',
        'postes_form_content_label': 'Content',
        'postes_button_cancel': 'Cancel',
        'postes_button_add_confirm': 'Add',
        // Jackpot additions
        'jackpot_screen_title': 'Jackpot - Member',
        'jackpot_breadcrumb_home': 'Home',
        'jackpot_breadcrumb_jackpot': 'Jackpot',
        'jackpot_button_coopt': 'Coopt a Talented Employee',
        'jackpot_search_hint': 'Search User',
        'jackpot_button_payment': 'Payment Request',
        'jackpot_earnings_title': 'Earnings',
        'jackpot_remaining_label': 'Total Remaining',
        'jackpot_withdrawn_label': 'Withdrawn',
        'jackpot_month_total': 'Total This Month',
        'jackpot_estimation_label': 'Estimation (daily + OneShot Bonus):',
        'jackpot_donut_not_earned': 'not earned',
        'jackpot_donut_auto': 'AUTO',
        'jackpot_prime_list_title': 'Prime List',
        'jackpot_prime_amount_label': 'Total prime Amount:',
        'jackpot_users_section': 'Linked users',
        'jackpot_table_user': 'User',
        'jackpot_table_daily_rate': 'Daily Rate',
        'jackpot_table_cra_status': 'CRA Status',
        'jackpot_table_type': 'Type',
        'jackpot_table_prime': 'Prime %',
        'jackpot_table_gain': 'Gain/Day',
        'jackpot_users_empty': 'No users found',
        // Calendar additions
        'holiday_new_year': 'New Year\'s Day',
        'holiday_labour_day': 'Labour Day',
        'holiday_victory_day': 'Victory Day',
        'holiday_bastille_day': 'Bastille Day',
        'holiday_assumption': 'Assumption',
        'holiday_all_saints': 'All Saints\' Day',
        'holiday_armistice': 'Armistice Day',
        'holiday_christmas': 'Christmas',
        'calendar_weekday_mon': 'Mon',
        'calendar_weekday_tue': 'Tue',
        'calendar_weekday_wed': 'Wed',
        'calendar_weekday_thu': 'Thu',
        'calendar_weekday_fri': 'Fri',
        'calendar_weekday_sat': 'Sat',
        'calendar_weekday_sun': 'Sun',
        'calendar_dialog_add_note': 'Add a note',
        'calendar_note_hint': 'Your note...',
        'calendar_button_close': 'Close',
        'calendar_button_add_note': 'Add Note',
        'calendar_empty_notes': 'No notes for this date',
        'calendar_legend_holiday': 'Holiday',
        'calendar_legend_personal_note': 'Personal note',
        'calendar_button_today': 'Today',
        // Feedback additions
        'feedback_screen_title': 'Feedback List',
        'feedback_breadcrumb_home': 'Home',
        'feedback_breadcrumb_communication': 'Communication',
        'feedback_breadcrumb_feedback': 'Feedback',
        'feedback_button_coopt': 'Coopt a Talented Employee',
        'feedback_tab_all': 'All',
        'feedback_tab_replied': 'Replied',
        'feedback_tab_unanswered': 'Unanswered',
        'feedback_month_select': 'Select Month',
        'feedback_search_hint': 'Search by user name',
        'feedback_table_user': 'User',
        'feedback_table_feedback': 'Feedback',
        'feedback_table_response': 'Response',
        'feedback_table_date': 'Date',
        'feedback_table_actions': 'Actions',
        'feedback_empty_message': 'No data to display',
        // Documents additions
        'documents_screen_title': 'Document Requests',
        'documents_breadcrumb_home': 'Home',
        'documents_breadcrumb_communication': 'Communication',
        'documents_breadcrumb_requests': 'Requests',
        'documents_button_coopt': 'Coopt a Talented Employee',
        'documents_tab_all': 'All',
        'documents_tab_replied': 'Replied',
        'documents_tab_unanswered': 'Unanswered',
        'documents_month_select': 'Select Month',
        'documents_empty_message': 'No data to display',
        // Applications additions
        'applications_screen_title': 'My Applications',
        'applications_breadcrumb_home': 'Home',
        'applications_breadcrumb_pages': 'Pages',
        'applications_breadcrumb_my_apps': 'My Applications',
        'applications_button_coopt': 'Coopt a Talented Employee',
        'applications_stat_total': 'Total',
        'applications_stat_init': 'Init',
        'applications_stat_in_progress': 'In Progress',
        'applications_stat_accepted': 'Accepted',
        'applications_search_label': 'Search',
        'applications_search_hint': 'Name, email, offer, status...',
        'applications_show_label': 'Show',
        'applications_table_candidate': 'Candidate',
        'applications_table_offer': 'Offer',
        'applications_table_date': 'Date',
        'applications_table_cv': 'CV',
        'applications_table_pipeline': 'Pipeline',
        'applications_table_status': 'Status',
        'applications_cv_view': 'View CV',
        'applications_cv_none': '—',
        'applications_empty_message': 'No data to display',
        // CRA screen
        'cra_banner_validation':
            'Please make sure to click the button to send the CRA for validation.',
        'cra_banner_attach': 'If you want to attach a signed client CRA:',
        'cra_button_import': 'Import CRA',
        'cra_banner_help_question': 'Don\'t know how to do it?',
        'cra_button_help_link': 'Click here',
        'cra_help_by': 'By Beeline',
        'cra_button_fill_click': 'Fill with One Click',
        'cra_filter_title': 'FILTER',
        'cra_filter_all': 'View all',
        'cra_filter_absence': 'Absence',
        'cra_filter_work': 'Work',
        'cra_legend_absence': 'Absence',
        'cra_legend_work': 'Work',
        'cra_calendar_hint': 'Click on a calendar day to enter your activity',
        'cra_selected_label': 'Selected:',
        // CRA Tracking additions
        'cra_tracking_screen_title': 'My CRA Tracking',
        'cra_tracking_subtitle': 'History of your activity reports',
        'cra_tracking_stat_submitted': 'Total submitted',
        'cra_tracking_stat_validated': 'Validated',
        'cra_tracking_stat_pending': 'Pending',
        'cra_tracking_stat_rejected': 'Rejected',
        'cra_tracking_table_period': 'Period',
        'cra_tracking_table_work_days': 'Work Days',
        'cra_tracking_table_absences': 'Absences',
        'cra_tracking_table_travels': 'Travels',
        'cra_tracking_table_submitted': 'Submitted on',
        'cra_tracking_table_status': 'Status',
        'cra_tracking_status_validated': 'Validated',
        'cra_tracking_status_pending': 'Pending',
        'cra_tracking_status_rejected': 'Rejected',
        'cra_tracking_dialog_work_days': 'Working days',
        'cra_tracking_dialog_absences': 'Absences',
        'cra_tracking_dialog_travels': 'Travels',
        'cra_tracking_dialog_status': 'Status',
        'cra_tracking_button_close': 'Close',
        // Additional common translations
        'days': 'days',
      },
      'fr': {
        'dashboard': 'Tableau de bord',
        'offer': 'Offre',
        'rh': 'RH',
        'personal': 'Personnel',
        'news': 'Actualités et Événements',
        'jackpot': 'Mon Jackpot',
        'applications': 'Mes Candidatures',
        'communication': 'Communication',
        'profile': 'Profil',
        'logout': 'Déconnexion',
        'my_cra': 'Mon CRA',
        'my_expenses': 'Mes Dépenses',
        'calendar': 'Calendrier',
        'my_tasks': 'Mes Tâches',
        'news_events': 'Actualités et Événements',
        'postes': 'Offres d\'emploi',
        'chats': 'Discussions',
        'feedbacks': 'Retours',
        'documents': 'Documents',
        'send_feedback': 'Envoyer un retour au support admin',
        'describe_feedback': 'Décrivez votre retour',
        'send': 'Envoyer',
        'feedback_sent': 'Retour envoyé avec succès!',
        'first_name': 'Prénom',
        'enter_first_name': 'Entrer le prénom',
        'last_name': 'Nom de famille',
        'enter_last_name': 'Entrer le nom de famille',
        'category': 'Catégorie',
        'select': 'Sélectionner...',
        'phone': 'Téléphone',
        'enter_phone': 'Entrer le téléphone',
        'email': 'Email',
        'enter_email': 'Entrer l\'email',
        'daily_role': 'Rôle quotidien',
        'enter_daily_role': 'Entrer le rôle quotidien',
        'summary': 'Résumé',
        'enter_summary': 'Entrer le résumé',
        'informations': 'Informations Générales',
        'domain_skills': 'Compétences du domaine',
        'professional_skills': 'Compétences professionnelles',
        'experiences': 'Expériences',
        'technical_skills': 'Compétences techniques',
        'education_history': 'Historique éducatif',
        'languages': 'Langues',
        'certifications': 'Certifications',
        'training': 'Formation',
        'save': 'Enregistrer',
        'add_new': 'Ajouter nouveau...',
        'no_items': 'Aucun élément ajouté',
        'offers': 'Offres',
        'apply': 'Postuler',
        'cra_tracking': 'Suivi CRA',
        'events': 'Événements',
        'cooptation': 'Ma Cooptation',
        'challenge': 'Mon Défi',
        'results': 'Mes Résultats',
        // Additional translations
        'add_task': 'Ajouter une tâche',
        'my_news': 'Actualités',
        'delete': 'Supprimer',
        'edit': 'Modifier',
        'close': 'Fermer',
        'cancel': 'Annuler',
        'search': 'Rechercher',
        'no_data': 'Aucune donnée disponible',
        'error': 'Erreur',
        'success': 'Succès',
        'loading': 'Chargement...',
        'empty': 'Vide',
        'back': 'Retour',
        'next': 'Suivant',
        'previous': 'Précédent',
        'view_all': 'Voir tout',
        'more': 'Plus',
        'less': 'Moins',
        'yes': 'Oui',
        'no': 'Non',
        'ok': 'OK',
        'company': 'Entreprise',
        'location': 'Localisation',
        'price': 'Prix',
        'type': 'Type',
        'remote': 'Télétravail',
        'hybrid': 'Hybride',
        'on_site': 'Sur site',
        'rate': 'Tarif',
        'description': 'Description',
        'posted_on': 'Posté le',
        'start_date': 'Date de début',
        'experience': 'Expérience',
        'candidates': 'Candidats',
        'expired': 'Expiré',
        'active': 'Actif',
        'pending': 'En attente',
        'completed': 'Complété',
        'in_progress': 'En cours',
        'online': 'En ligne',
        'offline': 'Hors ligne',
        'message': 'Message',
        'send_message': 'Envoyer un message',
        'type_message': 'Tapez votre message...',
        'document': 'Document',
        'upload': 'Télécharger',
        'download': 'Télécharger',
        'delete_confirm': 'Êtes-vous sûr de vouloir supprimer?',
        'expense': 'Dépense',
        'amount': 'Montant',
        'date': 'Date',
        'description_short': 'Desc.',
        'status': 'Statut',
        'no_conversations': 'Aucune conversation',
        'no_documents': 'Aucun document',
        'no_expenses': 'Aucune dépense',
        // Dashboard translations
        'statistics': 'Statistiques',
        'current_month': 'MOIS ACTUEL',
        'since_entry': 'DEPUIS L\'ENTRÉE',
        'total_ca': 'CA Total',
        'reserve': 'Réserve',
        'usable_reserve_ca': 'Réserve utilisable (CA)',
        'usable_reserve_days': 'Réserve utilisable (en jours)',
        'ca_since_entry': 'CA depuis l\'entrée',
        'reserve_since_entry': 'Réserve depuis l\'entrée',
        'usable_reserve_since_entry': 'Réserve utilisable depuis l\'entrée',
        'usable_reserve_since_entry_days':
            'Réserve utilisable depuis l\'entrée (en jours)',
        'congratulations': 'Félicitations',
        'my_cooptation_evolution': 'Mon évolution de cooptation',
        'evolution_per_year': 'Évolution par année',
        'scoring_chart': 'Graphique de notation',
        'evolution_application': 'Évolution des candidatures',
        'jackpot_report': 'Rapport Jackpot / Mois',
        'earned': 'Gagné',
        'withdrawn': 'Retiré',
        'leader_board': 'Classement',
        'your_rank': 'Votre rang est Top',
        // Profile translations
        'domain_skills_full': 'Compétences du domaine',
        'functional_skills': 'Compétences fonctionnelles',
        'level_beginner': 'Débutant',
        'level_intermediate': 'Intermédiaire',
        'level_advanced': 'Avancé',
        'level_expert': 'Expert',
        'add_skill': 'Ajouter une compétence',
        'skill_name': 'Nom de la compétence',
        'select_level': 'Sélectionner le niveau',
        'post': 'Poste',
        'position': 'Position',
        'daily_rate': 'Tarif quotidien',
        'education_degree': 'Diplôme',
        'education_school': 'École',
        'education_year': 'Année',
        'experience_title': 'Titre',
        'experience_company': 'Entreprise',
        'experience_start': 'Date de début',
        'experience_end': 'Date de fin',
        'experience_description': 'Description',
        'certification_name': 'Nom de la certification',
        'certification_org': 'Organisation',
        'certification_year': 'Année',
        'training_title': 'Titre',
        'training_org': 'Organisation',
        'training_year': 'Année',
        // News/Events translations
        'read_more': 'Lire plus',
        'published': 'Publié',
        'updated': 'Mis à jour',
        'breaking_news': 'Actualités importantes',
        'featured': 'Sélectionné',
        // Chat translations
        'no_contacts': 'Aucun contact',
        'start_conversation': 'Démarrer une conversation',
        'write_message': 'Écrivez votre message...',
        'message_sent': 'Message envoyé',
        // Offer translations
        'job_title': 'Titre du poste',
        'remote_work': 'Télétravail',
        'mode': 'Mode',
        'duration': 'Durée',
        'contract_type': 'Type de contrat',
        'required_skills': 'Compétences requises',
        'job_description': 'Description du poste',
        'cdd': 'Contrat à durée déterminée',
        'cdi': 'Contrat à durée indéterminée',
        'freelance': 'Freelance',
        'part_time': 'Temps partiel',
        // Expense translations
        'expense_date': 'Date de dépense',
        'expense_category': 'Catégorie',
        'expense_amount': 'Montant',
        'expense_description': 'Description',
        'total_expenses': 'Dépenses totales',
        'monthly_expenses': 'Dépenses mensuelles',
        // CRA translations
        'cra_period': 'Période CRA',
        'cra_status': 'Statut',
        'cra_rate': 'Tarif',
        'cra_hours': 'Heures',
        'cra_days': 'Jours',
        // Task translations
        'add_new_task': 'Ajouter une nouvelle tâche',
        'task_title': 'Titre de la tâche',
        'task_priority': 'Priorité',
        'task_deadline': 'Date limite',
        'task_status': 'Statut',
        'high': 'Haute',
        'medium': 'Moyenne',
        'low': 'Basse',
        'mark_complete': 'Marquer comme complété',
        'mark_important': 'Marquer comme important',
        'my_tasks_filter': 'Mes tâches',
        'important_tasks': 'Important',
        'completed_tasks': 'Complété',
        'deleted_tasks': 'Supprimé',
        // Login screen
        'login_welcome': 'Bienvenue sur Cooptalite ! 👋',
        'login_email_label': 'Email',
        'login_email_hint': 'jean',
        'login_password_label': 'Mot de passe',
        'login_password_forgot': 'Mot de passe oublié ?',
        'login_password_hint': '••••••••••',
        'login_button_signin': 'Se connecter',
        'login_guest_question': 'Freelance ou Employé ?',
        'login_guest_create': 'Créer un compte en tant qu\'invité',
        // Profile additions
        'profile_section_experiences': 'Expériences',
        'profile_company_name_hint': 'Nom de l\'entreprise',
        'profile_date_format': 'MM/AAAA',
        'profile_describe_role_hint': 'Décrivez votre rôle...',
        'profile_section_education': 'Historique éducatif',
        'profile_institution_hint': 'Institution',
        'profile_year_hint': 'ex. 2021',
        'profile_section_languages': 'Langues',
        'profile_add_language': 'Ajouter une langue',
        'profile_section_certifications': 'Certifications',
        'profile_section_training': 'Formation',
        // Offer screen
        'offers_list_title': 'Liste des offres',
        'offers_type_remote': 'Télétravail',
        'offers_type_hybrid': 'Hybride',
        'offers_type_onsite': 'Sur site',
        'offers_category_it': 'IT',
        'offers_category_network': 'Réseau',
        'offers_category_telecom': 'Télécommunication',
        'offers_category_dev': 'Développement',
        'offers_category_data': 'Data',
        'offers_category_cyber': 'Cybersécurité',
        'offers_category_devops': 'DevOps',
        'offers_category_infra': 'Infrastructure',
        'offers_category_pm': 'Gestion de projet',
        'offers_category_qa': 'Assurance qualité',
        'offers_category_sysinfo': 'Administration système',
        'offers_contract_cdd': 'CDD',
        'offers_contract_cdi': 'CDI',
        'offers_contract_freelance': 'Freelance',
        'offers_contract_parttime': 'Temps partiel',
        'offers_sort_rate_asc': 'Tarif ↑',
        'offers_sort_rate_desc': 'Tarif ↓',
        'offers_sort_start': 'Date de début',
        'offers_contact_prefix': 'Contact',
        // Chat additions
        'chat_search_hint': 'Rechercher ou démarrer une discussion',
        'chat_contacts_label': 'Contacts',
        'chat_online': 'En ligne',
        'chat_offline': 'Hors ligne',
        'chat_message_hint': 'Écrivez un message...',
        'chat_empty_title': 'Démarrer une conversation',
        // Expense additions
        'expense_category_transport': 'Transport',
        'expense_category_meal': 'Repas',
        'expense_category_accommodation': 'Hébergement',
        'expense_category_other': 'Autre',
        'expense_screen_title': 'Mes Dépenses',
        'expense_screen_subtitle': 'Gérez vos notes de frais',
        'expense_stat_total': 'Total',
        'expense_stat_count': 'Dépenses',
        'expense_search_hint': 'Rechercher...',
        'expense_filter_all': 'Tout',
        'expense_button_add': 'Ajouter une dépense',
        'expense_table_title': 'Titre',
        'expense_table_category': 'Catégorie',
        'expense_table_date': 'Date',
        'expense_table_amount': 'Montant',
        'expense_table_actions': 'Actions',
        'expense_empty_message': 'Aucune dépense trouvée',
        'expense_dialog_add_title': 'Ajouter une dépense',
        'expense_dialog_amount_label': 'Montant (€) *',
        // Events additions
        'events_breadcrumb_home': 'Accueil',
        'events_breadcrumb_actu': 'Actualités et Événements',
        'events_breadcrumb_list': 'Liste des événements',
        'events_filter_title': 'Recherche par titre :',
        'events_filter_start': 'Recherche par date de début :',
        'events_filter_end': 'Recherche par date de fin :',
        'events_date_format_hint': 'AAAA-MM-JJ',
        'events_empty_message': 'Aucun événement trouvé',
        'events_start_label': 'Début le',
        'events_end_label': 'Fin le',
        'events_no_image': 'Aucune image disponible',
        'events_button_details': 'Voir les détails',
        // Postes additions
        'postes_screen_title': 'Offres de postes',
        'postes_breadcrumb_home': 'Accueil',
        'postes_breadcrumb_postes': 'Postes',
        'postes_button_coopt': 'Coopter un employé talentueux',
        'postes_search_hint': 'Rechercher',
        'postes_button_add': 'Ajouter un post',
        'postes_button_view_my': 'Voir mes posts',
        'postes_empty_message': 'Aucun post trouvé',
        'postes_posted_by': 'Publié par :',
        'postes_comments_label': 'Commentaires',
        'postes_button_read_more': 'Lire plus',
        'postes_dialog_add_title': 'Ajouter un post',
        'postes_form_title_label': 'Titre *',
        'postes_form_content_label': 'Contenu',
        'postes_button_cancel': 'Annuler',
        'postes_button_add_confirm': 'Ajouter',
        // Jackpot additions
        'jackpot_screen_title': 'Jackpot - Membre',
        'jackpot_breadcrumb_home': 'Accueil',
        'jackpot_breadcrumb_jackpot': 'Jackpot',
        'jackpot_button_coopt': 'Coopter un employé talentueux',
        'jackpot_search_hint': 'Rechercher un utilisateur',
        'jackpot_button_payment': 'Demande de paiement',
        'jackpot_earnings_title': 'Gains',
        'jackpot_remaining_label': 'Total restant',
        'jackpot_withdrawn_label': 'Retiré',
        'jackpot_month_total': 'Total ce mois',
        'jackpot_estimation_label': 'Estimation (journalier + bonus unique) :',
        'jackpot_donut_not_earned': 'non gagné',
        'jackpot_donut_auto': 'AUTO',
        'jackpot_prime_list_title': 'Liste des primes',
        'jackpot_prime_amount_label': 'Montant total des primes :',
        'jackpot_users_section': 'Utilisateurs liés',
        'jackpot_table_user': 'Utilisateur',
        'jackpot_table_daily_rate': 'Tarif journalier',
        'jackpot_table_cra_status': 'Statut CRA',
        'jackpot_table_type': 'Type',
        'jackpot_table_prime': 'Prime %',
        'jackpot_table_gain': 'Gain/Jour',
        'jackpot_users_empty': 'Aucun utilisateur trouvé',
        // Calendar additions
        'holiday_new_year': 'Jour de l\'An',
        'holiday_labour_day': 'Fête du Travail',
        'holiday_victory_day': 'Victoire 1945',
        'holiday_bastille_day': 'Fête Nationale',
        'holiday_assumption': 'Assomption',
        'holiday_all_saints': 'Toussaint',
        'holiday_armistice': 'Armistice',
        'holiday_christmas': 'Noël',
        'calendar_weekday_mon': 'Lun',
        'calendar_weekday_tue': 'Mar',
        'calendar_weekday_wed': 'Mer',
        'calendar_weekday_thu': 'Jeu',
        'calendar_weekday_fri': 'Ven',
        'calendar_weekday_sat': 'Sam',
        'calendar_weekday_sun': 'Dim',
        'calendar_dialog_add_note': 'Ajouter une note',
        'calendar_note_hint': 'Votre note...',
        'calendar_button_close': 'Fermer',
        'calendar_button_add_note': 'Ajouter une note',
        'calendar_empty_notes': 'Aucune note pour cette date',
        'calendar_legend_holiday': 'Jour férié',
        'calendar_legend_personal_note': 'Note personnelle',
        'calendar_button_today': 'Aujourd\'hui',
        // Feedback additions
        'feedback_screen_title': 'Liste des retours',
        'feedback_breadcrumb_home': 'Accueil',
        'feedback_breadcrumb_communication': 'Communication',
        'feedback_breadcrumb_feedback': 'Retours',
        'feedback_button_coopt': 'Coopter un employé talentueux',
        'feedback_tab_all': 'Tous',
        'feedback_tab_replied': 'Répondu',
        'feedback_tab_unanswered': 'Sans réponse',
        'feedback_month_select': 'Sélectionner le mois',
        'feedback_search_hint': 'Rechercher par nom d\'utilisateur',
        'feedback_table_user': 'Utilisateur',
        'feedback_table_feedback': 'Retour',
        'feedback_table_response': 'Réponse',
        'feedback_table_date': 'Date',
        'feedback_table_actions': 'Actions',
        'feedback_empty_message': 'Aucune donnée à afficher',
        // Documents additions
        'documents_screen_title': 'Demandes de documents',
        'documents_breadcrumb_home': 'Accueil',
        'documents_breadcrumb_communication': 'Communication',
        'documents_breadcrumb_requests': 'Demandes',
        'documents_button_coopt': 'Coopter un employé talentueux',
        'documents_tab_all': 'Tous',
        'documents_tab_replied': 'Répondu',
        'documents_tab_unanswered': 'Sans réponse',
        'documents_month_select': 'Sélectionner le mois',
        'documents_empty_message': 'Aucune donnée à afficher',
        // Applications additions
        'applications_screen_title': 'Mes Candidatures',
        'applications_breadcrumb_home': 'Accueil',
        'applications_breadcrumb_pages': 'Pages',
        'applications_breadcrumb_my_apps': 'Mes Candidatures',
        'applications_button_coopt': 'Coopter un employé talentueux',
        'applications_stat_total': 'Total',
        'applications_stat_init': 'Init',
        'applications_stat_in_progress': 'En cours',
        'applications_stat_accepted': 'Accepté',
        'applications_search_label': 'Rechercher',
        'applications_search_hint': 'Nom, email, offre, statut...',
        'applications_show_label': 'Afficher',
        'applications_table_candidate': 'Candidat',
        'applications_table_offer': 'Offre',
        'applications_table_date': 'Date',
        'applications_table_cv': 'CV',
        'applications_table_pipeline': 'Pipeline',
        'applications_table_status': 'Statut',
        'applications_cv_view': 'Voir le CV',
        'applications_cv_none': '—',
        'applications_empty_message': 'Aucune donnée à afficher',
        // CRA screen
        'cra_banner_validation':
            'Assurez-vous de cliquer sur le bouton pour soumettre le CRA pour validation.',
        'cra_banner_attach': 'Si vous souhaitez joindre un CRA client signé:',
        'cra_button_import': 'Importer le CRA',
        'cra_banner_help_question': 'Vous ne savez pas comment faire?',
        'cra_button_help_link': 'Cliquez ici',
        'cra_help_by': 'Par Beeline',
        'cra_button_fill_click': 'Remplir en un clic',
        'cra_filter_title': 'FILTRE',
        'cra_filter_all': 'Afficher tout',
        'cra_filter_absence': 'Absence',
        'cra_filter_work': 'Travail',
        'cra_legend_absence': 'Absence',
        'cra_legend_work': 'Travail',
        'cra_calendar_hint':
            'Cliquez sur un jour du calendrier pour entrer votre activité',
        'cra_selected_label': 'Sélectionné:',
        // CRA Tracking additions
        'cra_tracking_screen_title': 'Mon suivi CRA',
        'cra_tracking_subtitle': 'Historique de vos rapports d\'activité',
        'cra_tracking_stat_submitted': 'Total soumis',
        'cra_tracking_stat_validated': 'Validé',
        'cra_tracking_stat_pending': 'En attente',
        'cra_tracking_stat_rejected': 'Rejeté',
        'cra_tracking_table_period': 'Période',
        'cra_tracking_table_work_days': 'Jours travaillés',
        'cra_tracking_table_absences': 'Absences',
        'cra_tracking_table_travels': 'Déplacements',
        'cra_tracking_table_submitted': 'Soumis le',
        'cra_tracking_table_status': 'Statut',
        'cra_tracking_status_validated': 'Validé',
        'cra_tracking_status_pending': 'En attente',
        'cra_tracking_status_rejected': 'Rejeté',
        'cra_tracking_dialog_work_days': 'Jours travaillés',
        'cra_tracking_dialog_absences': 'Absences',
        'cra_tracking_dialog_travels': 'Déplacements',
        'cra_tracking_dialog_status': 'Statut',
        'cra_tracking_button_close': 'Fermer',
        // Additional common translations
        'days': 'jours',
      },
    };

    return translations[_language]?[key] ?? key;
  }
}
