import 'package:flutter/material.dart';

class AppTheme extends ChangeNotifier {
  bool _isDarkMode = false;
  String _language = 'en'; // 'en' for English, 'fr' for French

  bool get isDarkMode => _isDarkMode;
  String get language => _language;

  void toggleDarkMode() {
    _isDarkMode = !_isDarkMode;
    notifyListeners();
  }

  void setLanguage(String lang) {
    _language = lang;
    notifyListeners();
  }

  ThemeData getTheme() {
    const primary = Color(0xFF1F4788); // Professional Blue
    const secondary = Color(0xFF00A3FF);
    const error = Color(0xFFE74C3C);

    if (_isDarkMode) {
      return ThemeData(
        useMaterial3: true,
        brightness: Brightness.dark,
        primaryColor: primary,
        scaffoldBackgroundColor: const Color(0xFF0F1419),
        colorScheme: const ColorScheme.dark(
          primary: primary,
          secondary: secondary,
          tertiary: Color(0xFF9E9E9E),
          error: error,
          surface: Color(0xFF1A1F2E),
          onSurface: Colors.white,
        ),
        // AppBar
        appBarTheme: const AppBarTheme(
          backgroundColor: Color(0xFF1A1F2E),
          elevation: 1,
          centerTitle: false,
          titleTextStyle: TextStyle(
            color: Colors.white,
            fontSize: 20,
            fontWeight: FontWeight.w600,
          ),
        ),
        // Text Themes
        textTheme: const TextTheme(
          headlineLarge: TextStyle(
            fontSize: 32,
            fontWeight: FontWeight.bold,
            color: Colors.white,
          ),
          headlineMedium: TextStyle(
            fontSize: 26,
            fontWeight: FontWeight.bold,
            color: Colors.white,
          ),
          headlineSmall: TextStyle(
            fontSize: 20,
            fontWeight: FontWeight.w600,
            color: Colors.white,
          ),
          titleLarge: TextStyle(
            fontSize: 18,
            fontWeight: FontWeight.w600,
            color: Colors.white,
          ),
          bodyLarge: TextStyle(
            fontSize: 16,
            fontWeight: FontWeight.w500,
            color: Colors.white,
          ),
          bodyMedium: TextStyle(
            fontSize: 14,
            fontWeight: FontWeight.normal,
            color: Color(0xFFB0B0B0),
          ),
          labelSmall: TextStyle(
            fontSize: 12,
            fontWeight: FontWeight.w500,
            color: Color(0xFF9E9E9E),
          ),
        ),
        // Button Themes
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            backgroundColor: primary,
            foregroundColor: Colors.white,
            padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(8),
            ),
            elevation: 2,
          ),
        ),
        // Input Decoration
        inputDecorationTheme: InputDecorationTheme(
          filled: true,
          fillColor: const Color(0xFF2D3546),
          hintStyle: const TextStyle(color: Color(0xFF9E9E9E)),
          labelStyle: const TextStyle(color: Color(0xFFB0B0B0)),
          contentPadding:
              const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(8),
            borderSide: const BorderSide(color: Color(0xFF2D3546)),
          ),
          enabledBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(8),
            borderSide: const BorderSide(color: Color(0xFF2D3546), width: 1),
          ),
          focusedBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(8),
            borderSide: const BorderSide(color: primary, width: 2),
          ),
        ),
        // Card Theme
        cardTheme: CardTheme(
          color: const Color(0xFF1A1F2E),
          elevation: 2,
          margin: EdgeInsets.zero,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12),
            side: const BorderSide(color: Color(0xFF2D3546), width: 1),
          ),
        ),
      );
    } else {
      return ThemeData(
        useMaterial3: true,
        brightness: Brightness.light,
        primaryColor: primary,
        scaffoldBackgroundColor: const Color(0xFFFAFAFC),
        colorScheme: const ColorScheme.light(
          primary: primary,
          secondary: secondary,
          tertiary: Color(0xFF616161),
          error: error,
          surface: Colors.white,
          onSurface: Color(0xFF1A1A1A),
        ),
        // AppBar
        appBarTheme: const AppBarTheme(
          backgroundColor: Colors.white,
          elevation: 1,
          centerTitle: false,
          titleTextStyle: TextStyle(
            color: Color(0xFF1A1A1A),
            fontSize: 20,
            fontWeight: FontWeight.w600,
          ),
        ),
        // Text Themes
        textTheme: const TextTheme(
          headlineLarge: TextStyle(
            fontSize: 32,
            fontWeight: FontWeight.bold,
            color: Color(0xFF1A1A1A),
          ),
          headlineMedium: TextStyle(
            fontSize: 26,
            fontWeight: FontWeight.bold,
            color: Color(0xFF1A1A1A),
          ),
          headlineSmall: TextStyle(
            fontSize: 20,
            fontWeight: FontWeight.w600,
            color: Color(0xFF1A1A1A),
          ),
          titleLarge: TextStyle(
            fontSize: 18,
            fontWeight: FontWeight.w600,
            color: Color(0xFF1A1A1A),
          ),
          bodyLarge: TextStyle(
            fontSize: 16,
            fontWeight: FontWeight.w500,
            color: Color(0xFF1A1A1A),
          ),
          bodyMedium: TextStyle(
            fontSize: 14,
            fontWeight: FontWeight.normal,
            color: Color(0xFF616161),
          ),
          labelSmall: TextStyle(
            fontSize: 12,
            fontWeight: FontWeight.w500,
            color: Color(0xFF9E9E9E),
          ),
        ),
        // Button Themes
        elevatedButtonTheme: ElevatedButtonThemeData(
          style: ElevatedButton.styleFrom(
            backgroundColor: primary,
            foregroundColor: Colors.white,
            padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(8),
            ),
            elevation: 2,
          ),
        ),
        // Input Decoration
        inputDecorationTheme: InputDecorationTheme(
          filled: true,
          fillColor: const Color(0xFFF5F5F5),
          hintStyle: const TextStyle(color: Color(0xFF9E9E9E)),
          labelStyle: const TextStyle(color: Color(0xFF616161)),
          contentPadding:
              const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(8),
            borderSide: const BorderSide(color: Color(0xFFDEE0E6)),
          ),
          enabledBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(8),
            borderSide: const BorderSide(color: Color(0xFFDEE0E6), width: 1),
          ),
          focusedBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(8),
            borderSide: const BorderSide(color: primary, width: 2),
          ),
        ),
        // Card Theme
        cardTheme: CardTheme(
          color: Colors.white,
          elevation: 2,
          margin: EdgeInsets.zero,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12),
            side: const BorderSide(color: Color(0xFFDEE0E6), width: 1),
          ),
        ),
      );
    }
  }

  String translate(String key) {
    final translations = {
      'en': {
        'dashboard': 'Dashboard',
        'offer': 'Offer',
        'rh': 'RH',
        'personal': 'Personal',
        'news': 'News & Events',
        'jackpot': 'My Jackpot',
        'applications': 'My Applications',
        'communication': 'Communication',
        'profile': 'Profile',
        'logout': 'Logout',
        'my_cra': 'My CRA',
        'my_expenses': 'My Expenses',
        'calendar': 'Calendar',
        'my_tasks': 'My Tasks',
        'news_events': 'News & Events',
        'postes': 'Job Offers',
        'chats': 'Chats',
        'feedbacks': 'Feedbacks',
        'documents': 'Documents',
        'send_feedback': 'Send feedback to admin support',
        'describe_feedback': 'Describe your feedback',
        'send': 'Send',
        'feedback_sent': 'Feedback sent successfully!',
        'first_name': 'First name',
        'enter_first_name': 'Enter first name',
        'last_name': 'Last name',
        'enter_last_name': 'Enter last name',
        'category': 'Category',
        'select': 'Select...',
        'phone': 'Phone',
        'enter_phone': 'Enter phone',
        'email': 'Email',
        'enter_email': 'Enter email',
        'daily_role': 'Daily Role',
        'enter_daily_role': 'Enter daily role',
        'summary': 'Summary',
        'enter_summary': 'Enter summary',
        'informations': 'General Information',
        'domain_skills': 'Domain Skills',
        'professional_skills': 'Professional Skills',
        'experiences': 'Experiences',
        'technical_skills': 'Technical Skills',
        'education_history': 'Education History',
        'languages': 'Languages',
        'certifications': 'Certifications',
        'training': 'Training',
        'save': 'Save',
        'add_new': 'Add New...',
        'no_items': 'No items added yet',
        'offers': 'Offers',
        'apply': 'Apply',
        'cra_tracking': 'CRA Tracking',
        'events': 'Events',
        'cooptation': 'My Cooptation',
        'challenge': 'My Challenge',
        'results': 'My Results',
        // Additional translations
        'add_task': 'Add Task',
        'my_news': 'News',
        'delete': 'Delete',
        'edit': 'Edit',
        'close': 'Close',
        'cancel': 'Cancel',
        'search': 'Search',
        'no_data': 'No data available',
        'error': 'Error',
        'success': 'Success',
        'loading': 'Loading...',
        'empty': 'Empty',
        'back': 'Back',
        'next': 'Next',
        'previous': 'Previous',
        'view_all': 'View All',
        'more': 'More',
        'less': 'Less',
        'yes': 'Yes',
        'no': 'No',
        'ok': 'OK',
        'company': 'Company',
        'location': 'Location',
        'price': 'Price',
        'type': 'Type',
        'remote': 'Remote',
        'hybrid': 'Hybrid',
        'on_site': 'On Site',
        'rate': 'Rate',
        'description': 'Description',
        'posted_on': 'Posted on',
        'start_date': 'Start Date',
        'experience': 'Experience',
        'candidates': 'Candidates',
        'expired': 'Expired',
        'active': 'Active',
        'pending': 'Pending',
        'completed': 'Completed',
        'in_progress': 'In Progress',
        'online': 'Online',
        'offline': 'Offline',
        'message': 'Message',
        'send_message': 'Send Message',
        'type_message': 'Type your message...',
        'document': 'Document',
        'upload': 'Upload',
        'download': 'Download',
        'delete_confirm': 'Are you sure you want to delete?',
        'expense': 'Expense',
        'amount': 'Amount',
        'date': 'Date',
        'description_short': 'Desc.',
        'status': 'Status',
        'no_conversations': 'No conversations',
        'no_documents': 'No documents',
        'no_expenses': 'No expenses',
        // Dashboard translations
        'statistics': 'Statistics',
        'current_month': 'CURRENT MONTH',
        'since_entry': 'SINCE ENTRY',
        'total_ca': 'Total CA',
        'reserve': 'Reserve',
        'usable_reserve_ca': 'Usable Reserve (CA)',
        'usable_reserve_days': 'Usable Reserve (in days)',
        'ca_since_entry': 'CA Since Entry',
        'reserve_since_entry': 'Reserve Since Entry',
        'usable_reserve_since_entry': 'Usable Reserve Since Entry',
        'usable_reserve_since_entry_days':
            'Usable Reserve Since Entry (in days)',
        'congratulations': 'Congratulations',
        'my_cooptation_evolution': 'My Cooptation Evolution',
        'evolution_per_year': 'Evolution Per Year',
        'scoring_chart': 'Scoring Chart',
        'evolution_application': 'Evolution Application',
        'jackpot_report': 'Jackpot Report / Month',
        'earned': 'Earned',
        'withdrawn': 'Withdrawn',
        'leader_board': 'Leader Board',
        'your_rank': 'Your rank is Top',
        // Profile translations
        'domain_skills_full': 'Domain Skills',
        'functional_skills': 'Functional Skills',
        'level_beginner': 'Beginner',
        'level_intermediate': 'Intermediate',
        'level_advanced': 'Advanced',
        'level_expert': 'Expert',
        'add_skill': 'Add Skill',
        'skill_name': 'Skill Name',
        'select_level': 'Select Level',
        'post': 'Post',
        'position': 'Position',
        'daily_rate': 'Daily Rate',
        'education_degree': 'Degree',
        'education_school': 'School',
        'education_year': 'Year',
        'experience_title': 'Title',
        'experience_company': 'Company',
        'experience_start': 'Start Date',
        'experience_end': 'End Date',
        'experience_description': 'Description',
        'certification_name': 'Certification Name',
        'certification_org': 'Organization',
        'certification_year': 'Year',
        'training_title': 'Title',
        'training_org': 'Organization',
        'training_year': 'Year',
        // News/Events translations
        'read_more': 'Read More',
        'published': 'Published',
        'updated': 'Updated',
        'breaking_news': 'Breaking News',
        'featured': 'Featured',
        // Chat translations
        'no_contacts': 'No contacts',
        'start_conversation': 'Start a conversation',
        'write_message': 'Write your message...',
        'message_sent': 'Message sent',
        // Offer translations
        'job_title': 'Job Title',
        'remote_work': 'Remote Work',
        'mode': 'Mode',
        'duration': 'Duration',
        'contract_type': 'Contract Type',
        'required_skills': 'Required Skills',
        'job_description': 'Job Description',
        'cdd': 'Fixed-term contract',
        'cdi': 'Permanent contract',
        'freelance': 'Freelance',
        'part_time': 'Part-time',
        // Expense translations
        'expense_date': 'Expense Date',
        'expense_category': 'Category',
        'expense_amount': 'Amount',
        'expense_description': 'Description',
        'total_expenses': 'Total Expenses',
        'monthly_expenses': 'Monthly Expenses',
        // CRA translations
        'cra_period': 'CRA Period',
        'cra_status': 'Status',
        'cra_rate': 'Rate',
        'cra_hours': 'Hours',
        'cra_days': 'Days',
        // Task translations
        'add_new_task': 'Add New Task',
        'task_title': 'Task Title',
        'task_priority': 'Priority',
        'task_deadline': 'Deadline',
        'task_status': 'Status',
        'high': 'High',
        'medium': 'Medium',
        'low': 'Low',
        'mark_complete': 'Mark as Complete',
        'mark_important': 'Mark as Important',
        'my_tasks_filter': 'My Tasks',
        'important_tasks': 'Important',
        'completed_tasks': 'Completed',
        'deleted_tasks': 'Deleted',
      },
      'fr': {
        'dashboard': 'Tableau de bord',
        'offer': 'Offre',
        'rh': 'RH',
        'personal': 'Personnel',
        'news': 'Actualités et Événements',
        'jackpot': 'Mon Jackpot',
        'applications': 'Mes Candidatures',
        'communication': 'Communication',
        'profile': 'Profil',
        'logout': 'Déconnexion',
        'my_cra': 'Mon CRA',
        'my_expenses': 'Mes Dépenses',
        'calendar': 'Calendrier',
        'my_tasks': 'Mes Tâches',
        'news_events': 'Actualités et Événements',
        'postes': 'Offres d\'emploi',
        'chats': 'Discussions',
        'feedbacks': 'Retours',
        'documents': 'Documents',
        'send_feedback': 'Envoyer un retour au support admin',
        'describe_feedback': 'Décrivez votre retour',
        'send': 'Envoyer',
        'feedback_sent': 'Retour envoyé avec succès!',
        'first_name': 'Prénom',
        'enter_first_name': 'Entrer le prénom',
        'last_name': 'Nom de famille',
        'enter_last_name': 'Entrer le nom de famille',
        'category': 'Catégorie',
        'select': 'Sélectionner...',
        'phone': 'Téléphone',
        'enter_phone': 'Entrer le téléphone',
        'email': 'Email',
        'enter_email': 'Entrer l\'email',
        'daily_role': 'Rôle quotidien',
        'enter_daily_role': 'Entrer le rôle quotidien',
        'summary': 'Résumé',
        'enter_summary': 'Entrer le résumé',
        'informations': 'Informations Générales',
        'domain_skills': 'Compétences du domaine',
        'professional_skills': 'Compétences professionnelles',
        'experiences': 'Expériences',
        'technical_skills': 'Compétences techniques',
        'education_history': 'Historique éducatif',
        'languages': 'Langues',
        'certifications': 'Certifications',
        'training': 'Formation',
        'save': 'Enregistrer',
        'add_new': 'Ajouter nouveau...',
        'no_items': 'Aucun élément ajouté',
        'offers': 'Offres',
        'apply': 'Postuler',
        'cra_tracking': 'Suivi CRA',
        'events': 'Événements',
        'cooptation': 'Ma Cooptation',
        'challenge': 'Mon Défi',
        'results': 'Mes Résultats',
        // Additional translations
        'add_task': 'Ajouter une tâche',
        'my_news': 'Actualités',
        'delete': 'Supprimer',
        'edit': 'Modifier',
        'close': 'Fermer',
        'cancel': 'Annuler',
        'search': 'Rechercher',
        'no_data': 'Aucune donnée disponible',
        'error': 'Erreur',
        'success': 'Succès',
        'loading': 'Chargement...',
        'empty': 'Vide',
        'back': 'Retour',
        'next': 'Suivant',
        'previous': 'Précédent',
        'view_all': 'Voir tout',
        'more': 'Plus',
        'less': 'Moins',
        'yes': 'Oui',
        'no': 'Non',
        'ok': 'OK',
        'company': 'Entreprise',
        'location': 'Localisation',
        'price': 'Prix',
        'type': 'Type',
        'remote': 'Télétravail',
        'hybrid': 'Hybride',
        'on_site': 'Sur site',
        'rate': 'Tarif',
        'description': 'Description',
        'posted_on': 'Posté le',
        'start_date': 'Date de début',
        'experience': 'Expérience',
        'candidates': 'Candidats',
        'expired': 'Expiré',
        'active': 'Actif',
        'pending': 'En attente',
        'completed': 'Complété',
        'in_progress': 'En cours',
        'online': 'En ligne',
        'offline': 'Hors ligne',
        'message': 'Message',
        'send_message': 'Envoyer un message',
        'type_message': 'Tapez votre message...',
        'document': 'Document',
        'upload': 'Télécharger',
        'download': 'Télécharger',
        'delete_confirm': 'Êtes-vous sûr de vouloir supprimer?',
        'expense': 'Dépense',
        'amount': 'Montant',
        'date': 'Date',
        'description_short': 'Desc.',
        'status': 'Statut',
        'no_conversations': 'Aucune conversation',
        'no_documents': 'Aucun document',
        'no_expenses': 'Aucune dépense',
        // Dashboard translations
        'statistics': 'Statistiques',
        'current_month': 'MOIS ACTUEL',
        'since_entry': 'DEPUIS L\'ENTRÉE',
        'total_ca': 'CA Total',
        'reserve': 'Réserve',
        'usable_reserve_ca': 'Réserve utilisable (CA)',
        'usable_reserve_days': 'Réserve utilisable (en jours)',
        'ca_since_entry': 'CA depuis l\'entrée',
        'reserve_since_entry': 'Réserve depuis l\'entrée',
        'usable_reserve_since_entry': 'Réserve utilisable depuis l\'entrée',
        'usable_reserve_since_entry_days':
            'Réserve utilisable depuis l\'entrée (en jours)',
        'congratulations': 'Félicitations',
        'my_cooptation_evolution': 'Mon évolution de cooptation',
        'evolution_per_year': 'Évolution par année',
        'scoring_chart': 'Graphique de notation',
        'evolution_application': 'Évolution des candidatures',
        'jackpot_report': 'Rapport Jackpot / Mois',
        'earned': 'Gagné',
        'withdrawn': 'Retiré',
        'leader_board': 'Classement',
        'your_rank': 'Votre rang est Top',
        // Profile translations
        'domain_skills_full': 'Compétences du domaine',
        'functional_skills': 'Compétences fonctionnelles',
        'level_beginner': 'Débutant',
        'level_intermediate': 'Intermédiaire',
        'level_advanced': 'Avancé',
        'level_expert': 'Expert',
        'add_skill': 'Ajouter une compétence',
        'skill_name': 'Nom de la compétence',
        'select_level': 'Sélectionner le niveau',
        'post': 'Poste',
        'position': 'Position',
        'daily_rate': 'Tarif quotidien',
        'education_degree': 'Diplôme',
        'education_school': 'École',
        'education_year': 'Année',
        'experience_title': 'Titre',
        'experience_company': 'Entreprise',
        'experience_start': 'Date de début',
        'experience_end': 'Date de fin',
        'experience_description': 'Description',
        'certification_name': 'Nom de la certification',
        'certification_org': 'Organisation',
        'certification_year': 'Année',
        'training_title': 'Titre',
        'training_org': 'Organisation',
        'training_year': 'Année',
        // News/Events translations
        'read_more': 'Lire plus',
        'published': 'Publié',
        'updated': 'Mis à jour',
        'breaking_news': 'Actualités importantes',
        'featured': 'Sélectionné',
        // Chat translations
        'no_contacts': 'Aucun contact',
        'start_conversation': 'Démarrer une conversation',
        'write_message': 'Écrivez votre message...',
        'message_sent': 'Message envoyé',
        // Offer translations
        'job_title': 'Titre du poste',
        'remote_work': 'Télétravail',
        'mode': 'Mode',
        'duration': 'Durée',
        'contract_type': 'Type de contrat',
        'required_skills': 'Compétences requises',
        'job_description': 'Description du poste',
        'cdd': 'Contrat à durée déterminée',
        'cdi': 'Contrat à durée indéterminée',
        'freelance': 'Freelance',
        'part_time': 'Temps partiel',
        // Expense translations
        'expense_date': 'Date de dépense',
        'expense_category': 'Catégorie',
        'expense_amount': 'Montant',
        'expense_description': 'Description',
        'total_expenses': 'Dépenses totales',
        'monthly_expenses': 'Dépenses mensuelles',
        // CRA translations
        'cra_period': 'Période CRA',
        'cra_status': 'Statut',
        'cra_rate': 'Tarif',
        'cra_hours': 'Heures',
        'cra_days': 'Jours',
        // Task translations
        'add_new_task': 'Ajouter une nouvelle tâche',
        'task_title': 'Titre de la tâche',
        'task_priority': 'Priorité',
        'task_deadline': 'Date limite',
        'task_status': 'Statut',
        'high': 'Haute',
        'medium': 'Moyenne',
        'low': 'Basse',
        'mark_complete': 'Marquer comme complété',
        'mark_important': 'Marquer comme important',
        'my_tasks_filter': 'Mes tâches',
        'important_tasks': 'Important',
        'completed_tasks': 'Complété',
        'deleted_tasks': 'Supprimé',
      },
    };

    return translations[_language]?[key] ?? key;
  }
}
